os:
  - linux
language: java
jdk:
  - oraclejdk8
sudo: false
cache:
  directories:
    - $HOME/.m2
env:
  global:
    - NODE_VERSION=8.9.4
    - SPRING_OUTPUT_ANSI_ENABLED=ALWAYS
    - SPRING_JPA_SHOW_SQL=false
before_install:
  - jdk_switcher use oraclejdk8
  - java -version
notifications:
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
deploy:
   provider: cloudfoundry
   username: mirchiseth+cf@gmail.com
   password: supersecretpassword
   api: https://api.cf.us10.hana.ondemand.com
   organization: P2000174221trial_trial
   space: dev
